version: '3'

services:
  web:
    container_name: wsgi
    build: .
    command: pytest
    volumes:
      - ./:/usr/src/api/
    ports:
      - 5555:5555
    env_file:
      - ./env/.env.test
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./create_db.sh:/docker-entrypoint-initdb.d/create_db.sh

    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1337
        - POSTGRES_DB=postgres
        - DB_NAME=app_test

volumes:
    postgres_data: